apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: dmoore31flask
  namespace: dmoore31
  labels: 
    app:  dmoore31flask 
spec: 
  selector: 
    matchLabels: 
      app: dmoore31flask
  replicas: 1 
  strategy: 
    rollingUpdate: 
      maxSurge: 25% 
      maxUnavailable: 25% 
    type: RollingUpdate 
  template: 
    metadata: 
      labels: 
        app:  dmoore31flask
    spec: 
      containers: 
      - name:  dmoore31flask
        image:  dmoore31/flask_app 
        resources: 
          requests: 
            cpu: 100m 
            memory: 100Mi 
          limits: 
            cpu: 100m 
            memory: 100Mi 
        ports: 
        - containerPort:  5000 
          name:  dmoore31flask 
        imagePullPolicy: Always 
      restartPolicy: Always 
 
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: flaskcontainer 
  namespace: dmoore31
spec: 
  selector: 
    app: flaskcontainer 
  type: LoadBalancer 
  sessionAffinity: None 
  sessionAffinityConfig: 
    clientIP: 
      timeoutSeconds: 10800 
  ports: 
  - name: flaskcontainer 
    protocol: TCP 
    port: 80 
    targetPort: 5000 